name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  push: {branches: ["main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: creator54
          template: classic
          config_animations: yes
          config_timezone: Asia/Kolkata
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: user
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed
          plugin_habits: yes
          plugin_habits_from: 250
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          plugin_activity_visibility: public
