name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: creator54
          template: classic
          # base: repositories,metadata
          # base: metadata
          config_animations: yes
          config_timezone: India/Kolkata
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: user
            #plugin_stars: yes
            #plugin_stars_limit: 4
          #plugin_languages: yes
          #plugin_languages_details: bytes-size, percentage
          #plugin_languages_limit: 10
          plugin_achievements: yes
          plugin_achievements_threshold: B       # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets params
          plugin_achievements_display: detailed
          plugin_activity_visibility: public
          plugin_habits: yes
          plugin_habits_from: 250
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          #plugin_notable: yes
          #plugin_notable_indepth: yes
          #plugin_notable_repositories: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create

